# Generated by Django 4.1.6 on 2023-02-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'APPLIED'), ('SCREENING', 'SCREENING'), ('FIRST INTERVIEW', 'FIRST INTERVIEW'), ('ON PROCESS', 'ON PROCESS'), ('OFFER', 'OFFER')], default='APPLIED', max_length=20),
        ),
    ]
